node-ts/bus

- packages/bus-core/src/bus-module.ts
- packages/bus-core/src/service-bus/message-attributes.ts
In the past, user would have to speculate whether `attributes` and `stickyAttributes` are undefined. 
This PR fixes this
> Improved typedef of MessageAttributes to ease usage

- packages/bus-postgres/src/postgres-persistence.integration.ts
- packages/bus-postgres/src/postgres-persistence.ts
PostgreSQL 9.4 does not support `create index XX if not exist`
This PR uses older syntax for this feature so bus-postgres can work with PG 9.4.
I have ran the test for bus-postgres manually and it was successful.
> Make bus-postgres compatible with PG 9.4 when creating index

- packages/bus-core/src/handler/handler.integration.ts
- packages/bus-core/src/transport/memory-queue.spec.ts
- packages/bus-core/src/transport/memory-queue.ts
- packages/bus-core/src/transport/transport.ts
- packages/bus-rabbitmq/src/rabbitmq-transport.integration.ts
- packages/bus-rabbitmq/src/rabbitmq-transport.ts
- packages/bus-sqs/src/sqs-transport.integration.ts
- packages/bus-sqs/src/sqs-transport.ts
- packages/bus-sqs/test/test-command-handler.ts
- packages/bus-workflow/src/workflow/workflow.integration.ts
A number of integration tests were failing to run due to movements of classes between packages.
These have been fixed, re-run and are now passing again. There were no failures in the tests themselves at any point.
> Fix failing tests

- packages/bus-core/src/service-bus/service-bus.ts
Hey there,
first of all: I really like the basics of the approach you're following, great job so far!
When trying to do a first example (one simple command, handled by a handler, emitting an event with a listener attached) I also wanted to test the bus' behavior in case a handler throws an error - basically when something goes wrong during processing. 
And this is what I found:
Since `ServiceBus:dispatchMessageToHandler` didn't return the Promise of `handler.handle(message, context)` `handlersToInvoke` in `ServiceBus:dispatchMessageToHandlers` contained an array of Promise<undefined> so a handler error never got to the catch block in `ServiceBus:handleNextMessage`, thus the message was always deleted from instead of returned to the transport in case of an error (super dangerous in …
> Fix error handling for handlers

- packages/bus-core/src/service-bus/service-bus.integration.ts
- packages/bus-core/src/test/test-container.ts
- packages/bus-core/src/util/assert-unreachable.ts
- packages/bus-core/src/util/index.ts
- tsconfig.json
As pointed out by @dropdevcoding in https://github.com/node-ts/bus/pull/41, any errors thrown by message handlers aren't caught and would be reported as an unhandled application exception with the message discarded.
This MR just adds a failing test to highlight the current bug, which should then start passing once https://github.com/node-ts/bus/pull/41 has been merged in.
> Add tests for handler errors

- packages/bus-core/src/application-bootstrap/application-bootstrap.spec.ts
- packages/bus-core/src/application-bootstrap/application-bootstrap.ts
- packages/bus-core/src/handler/handler-registry.spec.ts
- packages/bus-core/src/handler/handler-registry.ts
- packages/bus-core/src/handler/handler.ts
- packages/bus-core/src/handler/handles-message.ts
- packages/bus-core/src/handler/index.ts
- packages/bus-core/src/test/test-resolver-handler.ts
- packages/bus-core/src/transport/memory-queue.spec.ts
- packages/bus-core/src/transport/memory-queue.ts
- packages/bus-rabbitmq/src/rabbitmq-transport.integration.ts
- packages/bus-rabbitmq/src/rabbitmq-transport.ts
- packages/bus-rabbitmq/test/test-system-message-handler.ts
- packages/bus-rabbitmq/test/test-system-message.ts
- packages/bus-sqs/src/sqs-transport.integration.ts
- packages/bus-sqs/src/sqs-transport.ts
- packages/bus-sqs/test/test-system-message-handler.ts
- packages/bus-sqs/test/test-system-message.ts
- packages/bus-workflow/src/workflow/decorators/handles.ts
- packages/bus-workflow/src/workflow/message-workflow-mapping.ts
This is an enhancement for the system message resolvers that allows the handler to specify which topic identifier the system messages are sourced from. This allows the library to subscribe queues to topics instead of doing this manually through infrastructure scripts.
It assumes that the topic is pre-existing as the application is no longer the owner of the topic. Ie: it assumes system messages are produced and topics/exchanges created by the external systems.
> Provide topic identifier for system messages

- packages/bus-postgres/README.md
Hi,
was testing your sample project to get it to work with other transport layers. Found that the PostgreSQL example was having a few TS compiler errors.
> Fixed PostgreSQL transport example

- package.json
- packages/bus-core/src/application-bootstrap/application-bootstrap.ts
- packages/bus-core/src/bus-module.ts
- packages/bus-core/src/bus-symbols.ts
- packages/bus-core/src/handler/handler-registry.spec.ts
- packages/bus-core/src/handler/handler-registry.ts
- packages/bus-core/src/serialization/index.ts
- packages/bus-core/src/serialization/message-serializer.spec.ts
- packages/bus-core/src/serialization/message-serializer.ts
- packages/bus-core/src/transport/memory-queue.ts
- packages/bus-core/src/transport/transport.ts
- packages/bus-rabbitmq/src/rabbitmq-transport.ts
- packages/bus-sqs/package.json
- packages/bus-sqs/src/sqs-transport.integration.ts
- packages/bus-sqs/src/sqs-transport.ts
- packages/bus-sqs/test/test-command.ts
This PR changes SQS transport to use Bus.Serializer to handle its message serialization/deserialization. 
This PR also refactor `Transport` so its `initialize` function doesn't require `handlerRegistry`. We hope the implementation take `handlerRegistry` from container.
> Allow SQS Transport to use Bus.Serializer to (de)serialization

- packages/bus-sqs/src/sqs-transport.ts
This PR makes sure when Bus initialize the system, it will update services queue's attributes even when the service queue is pre existent.
> Sync SQS Attributes for existing SQS queue

- packages/bus-core/src/service-bus/bus-hooks.ts
- packages/bus-core/src/service-bus/bus.ts
- packages/bus-core/src/service-bus/service-bus.integration.ts
- packages/bus-core/src/service-bus/service-bus.ts
This PR modifies error hook so that full message body was provided as the forth parameter.
The goal of such change is to allow consumer to access more information while handling error. An example is that, consumer might want to decide whether to spit out an error log based on how many times the message has been retried.
> Provide raw message to error hook

- packages/bus-workflow/src/workflow/registry/workflow-handler-proxy.ts
When you have multiple workflows registered, log files will get inundated with "No existing workflow data found for message. Ignoring. [object Object]" messages. We get tons of these messages since we have multiple workflows wired up in our service. Thanks!
> Downgrade log message

- packages/bus-sqs/src/sqs-transport-configuration.ts
- packages/bus-sqs/src/sqs-transport.ts
This PR exposes SQS receive's wait time via config. 
Use cases: 
- Reduce shut down duration 
- Turn long polling to short polling
> Expose sqs wait time via config

- packages/bus-redis/README.md
- packages/bus-redis/package.json
- packages/bus-redis/src/bus-redis-module.ts
- packages/bus-redis/src/bus-redis-symbols.ts
- packages/bus-redis/src/redis-transport-configuration.ts
- packages/bus-redis/src/redis-transport.integration.ts
- packages/bus-redis/src/redis-transport.ts
- packages/bus-redis/tsconfig.json
- tsconfig.json
- yarn.lock
Proposing moving from bullmq to a much simpler queue implementation: https://gitlab.com/ersutton/modest-queue
had some issues with bullmq when processing messages, when you set a job to be completed, it would automatically pop the next message to be processed off the queue - which would have made the implementation in this library messy.
This MR
* migrates to modest-queue
* publishes messages to any queue that has stated that it wants to know about a certain message
Tests pass:
> Migrating to modest queue

- packages/bus-core/src/application-bootstrap/application-bootstrap.ts
- packages/bus-core/src/transport/transport.ts
- packages/bus-rabbitmq/src/rabbitmq-transport.ts
- packages/bus-redis/src/redis-transport-configuration.ts
- packages/bus-redis/src/redis-transport.ts
`.initializeSendOnly()` was trying to create app & dlqs. In reality it should only do enough setup to allow the library to connect and send a message only. 
This fix introduces `connect()` `disconnect()` to the transport definition so that the transport implementation can be more specific around how it starts up.
> Fix sendonly initialization

- packages/bus-redis/README.md
- packages/bus-redis/src/redis-transport-configuration.ts
- packages/bus-redis/src/redis-transport.ts
For proper separation of test environment and local environment, and also to support multiple applications running on the same redis instance, it would be good to have the prefix be configurable.
All tests still pass, and this is a backwards compatible change.
> bus-redis - add the ability to configure the subscriptionsKeyPrefix

- packages/bus-core/src/index.ts
- packages/bus-core/src/transport/memory-queue.spec.ts
- packages/bus-core/src/transport/memory-queue.ts
Fix for #162 
Because `.fail()` internally deletes the message, when the handler finishes it will also try to delete the message by its new index (-1). Because the delete operation is a splice from the array; any messages between -1 and 1 are deleted.
Other transports don't have this issue since the deletion is made using the receiptId/messageId
> Fix: Memory queue fail deletes other messages

- packages/bus-core/src/container/container-adapter.spec.ts
- packages/bus-core/src/handler/error/handler-dispatch-rejected.ts
- packages/bus-core/src/handler/error/index.ts
- packages/bus-core/src/service-bus/bus-instance.ts
- packages/bus-core/src/workflow/registry/workflow-registry.ts
- packages/bus-sqs/src/sqs-transport.ts
Closes #126 
This uses `promise.allSettled()` instead of `promise.all()` when dispatching the same message to multiple handlers on the same instance. This is done as there is no coupling between handlers and failure in one shouldn't affect processing in another.
Note that this still throws all errors from the dispatch that are now inside the `HandlerDispatchRejected` error in the `reasons` attribute.
The  message will still be retried, so it's still important as always to ensure message handling is idempotent.
> #126 - Use promise.allSettled() during message dispatch

- packages/bus-core/src/workflow/registry/workflow-registry.ts
Closes #157 
When a `ContainerAdapter` is provided, it should be used when getting workflow instances to dispatch messages to.  Depending on the IoC container, fetching a Workflow instance that hasn't been registered with the container should throw a descriptive error and encourage the consumer to register it.
When a `ContainerAdapter` is not provided, the system should fallback to manually constructing the workflow
> Use container to get workflows

- packages/bus-core/src/workflow/registry/workflow-registry.spec.ts
- packages/bus-core/src/workflow/registry/workflow-registry.ts
Closes #157 
A continuation of #169 
When a `ContainerAdapter` is provided, it should be used when getting workflow instances to dispatch messages to.  Depending on the IoC container, fetching a Workflow instance that hasn't been registered with the container should throw a descriptive error and encourage the consumer to register it.
When a `ContainerAdapter` is not provided, the system should fallback to manually constructing the workflow
> 157 - addendum 

- .gitignore
- .vscode/launch.json
- .vscode/settings.json
- packages/bus-core/src/index.ts
- packages/bus-core/src/service-bus/bus-configuration.ts
- packages/bus-core/src/service-bus/bus-instance.ts
- packages/bus-core/src/transport/transport.ts
- packages/bus-rabbitmq/src/rabbitmq-transport.ts
- packages/bus-test/package.json
This is a fix for #175 where a consumer of an empty rabbitmq queue will see high CPU. This is due to an implementation that relied on amqplib's `channel.get()` that returns immediately regardless if a message is queued or not. As a result this was being called repeatedly causing the high CPU spin (evidenced by less CPU when a .sleep() was added)
This change uses `.consume()` instead which is callback based and only triggers when a message is available for consumption. As a result there is no repeated spinning waiting for a message.
> #175  - Fix high cpu for rabbitmq consumers

- .vscode/settings.json
- packages/bus-class-serializer/package.json
- packages/bus-class-serializer/src/class-serializer.ts
- packages/bus-sqs/package.json
- packages/bus-test/package.json
- yarn.lock
This PR bumps the `class-transformer` dependency from 0.3.1 -> 0.5.1. 
0.3.2, 0.4.0, 0.50 and 0.51 all had "breaking changes", although they are minimal: https://github.com/typestack/class-transformer/blob/develop/CHANGELOG.md
The objective is to suppress warnings in consuming project build output, fixed in 0.3.2:
```bash
WARNING in ../../node_modules/.pnpm/class-transformer@0.3.1/node_modules/class-transformer/storage.js
Module Warning (from ../../node_modules/.pnpm/source-map-loader@3.0.1_webpack@5.74.0/node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/x-project/node_modules/.pnpm/class-transformer@0.3.1/node_modules/src/storage.ts' file: Error: ENOENT: no such file or directory, open '/x-project/node_modules/.pnpm/class-transformer@0.3.1/node_modules/src/sto …
```
> Upgrade class-transformer to 0.5.1

- packages/bus-core/src/container/container-adapter.spec.ts
- packages/bus-core/src/container/container-adapter.ts
- packages/bus-core/src/service-bus/bus-configuration.ts
- packages/bus-core/src/service-bus/bus-instance.ts
- packages/bus-core/src/workflow/registry/workflow-registry.spec.ts
- packages/bus-core/src/workflow/registry/workflow-registry.ts
Since some IoC containers such as loopback and Nest JS are async and returns promises. I have added support of this without breaking the previous code for existing users.  
The applied changes are as below: 
* Update container adapter interface to support both promise and non promises.
* Update the bus configuration and bus instance to handle promises in
* Add new unit tests for async container in adapter and workflow.
> Support async resolvers in container.

- packages/bus-mongodb/README.md
- packages/bus-mongodb/package.json
- packages/bus-mongodb/src/error/index.ts
- packages/bus-mongodb/src/error/workflow-state-not-found.ts
- packages/bus-mongodb/src/index.ts
- packages/bus-mongodb/src/mongodb-configuration.ts
- packages/bus-mongodb/src/mongodb-persistence.integration.ts
- packages/bus-mongodb/src/mongodb-persistence.ts
- packages/bus-mongodb/test/index.ts
- packages/bus-mongodb/test/run-task.ts
- packages/bus-mongodb/test/task-ran.ts
- packages/bus-mongodb/test/test-command.ts
- packages/bus-mongodb/test/test-workflow-state.ts
- packages/bus-mongodb/test/test-workflow.ts
- packages/bus-mongodb/tsconfig.json
- packages/bus-mongodb/tslint.json
- yarn.lock
I was using the library workflow part and came across the case where I needed to use Mongodb as a persistence for states. 
High level changes: 
* Add new package for @node-ts/bus-mongodb.
* Add mongodb configuration.
* Add mongodb persistence.
* Add integration tests for mongodb.
@adenhertog  I have copied this implementation from bus-postgres package that exists in the project.
> FIX #200: Support Mongodb Persistence for WF

- packages/bus-core/package.json
- packages/bus-core/src/message-handling-context/message-handling-context.spec.ts
- packages/bus-core/src/message-handling-context/message-handling-context.ts
- packages/bus-core/src/service-bus/bus-instance-concurrency.integration.ts
- packages/bus-core/src/service-bus/bus-instance.ts
- packages/bus-core/src/workflow/registry/workflow-registry.ts
- packages/bus-core/src/workflow/started.spec.ts
- packages/bus-core/src/workflow/workflow-concurrency.integration.ts
- pnpm-lock.yaml
Replaces the 'async_hooks' implementation of 'message-handling-context' with 'cli-hooked'.
There's a suspicion that the message-handling-context is leaking message contexts when used in highly parallel services. This can cause issued with handlers that depend on message attributes, particularly workflows that are mapped using correlationIds, to become out of sync.
'cli-hooked' has been integrated, which under the hood still uses the native node 'async_hooks', however does it in a much better tested and solid way. 
Tests have been introduced to illustrate that no context has been leaked when running multiple instances of a workflow in parallel.
> Replace async_hooks with cli-hooked

- packages/bus-core/package.json
- packages/bus-core/src/message-handling-context/message-handling-context.spec.ts
- packages/bus-core/src/message-handling-context/message-handling-context.ts
- packages/bus-core/src/service-bus/bus-instance.ts
- packages/bus-core/src/workflow/registry/workflow-registry.ts
- pnpm-lock.yaml
Removes cls-hooked and replaces with alscontext
The cls-hooked library is unmaintained, and when used with promises/async fails to dispose the context correctly and leaks memory.
- https://github.com/Jeff-Lewis/cls-hooked/issues/63
- https://github.com/Jeff-Lewis/cls-hooked/issues/66
`alscontext` is used in this change, which from observation doesn't have the same issue.
> Cutover message handling context to ALS Context

- packages/bus-core/src/workflow/registry/workflow-registry.ts
This PR upgrades the current log from warn to error so that it hits our production logs for greater visibility.
> Upgrade 'no existing workflow state' log from warn to error

- packages/bus-core/src/workflow/registry/workflow-registry.ts
- packages/bus-core/src/workflow/test/test-discarded-workflow.ts
- packages/bus-core/src/workflow/test/test-void-startedby-workflow.ts
- packages/bus-core/src/workflow/workflow-startedby.integration.ts
Fixes `this.discard()` not discarding workflow changes, particularly in startedBy handlers where workflow state should not be persisted.
Previously a workflow state was still being written to persistence when calling this, which was incorrect.
> Fix .discard() still persisting workflow data

- packages/bus-core/package.json
- packages/bus-core/src/service-bus/bus-instance-outboxing.integration.ts
- packages/bus-core/src/service-bus/bus-instance.ts
- packages/bus-core/src/test/test-event.ts
Adds message to an outbox when calling bus.send/bus.publish from within a handler, and only dispatches messages when the handler resolves.
Outboxing is useful for when a handler fails to completely handle a message, and no actions should be committed so that the message can be retried cleanly. This includes workflows where in a high concurrency environments, competing updates to a single workflow may fail and the message needs to be retried without sending any subsequent messages on each attempt.
> Outbox all handler-based message publications

- packages/bus-core/package.json
- packages/bus-core/src/service-bus/bus-instance-outboxing.integration.ts
- packages/bus-core/src/service-bus/bus-instance.ts
Adds messages to an in-memory array as the outbox queue, and dispatches using a worker pool
Previously for handlers that sent high volumes of messages (eg, 10K+), the messages would be outboxed as anon async functions. These were previously dispatched using a single Promise.all(), which causes heap exhaustion particularly in low-mem environments.
This update provides the same final behaviour, but does it in a more memory-efficient way.
> Dispatch outbox using worker queue

- packages/bus-core/package.json
- packages/bus-core/src/error/fail-message-outside-handling-context.ts
- packages/bus-core/src/error/index.ts
- packages/bus-core/src/error/return-message-outside-handling-context.ts
- packages/bus-core/src/message-lifecycle-context/index.ts
- packages/bus-core/src/message-lifecycle-context/message-lifecycle-context.ts
- packages/bus-core/src/service-bus/bus-instance-return-message.integration.ts
- packages/bus-core/src/service-bus/bus-instance.integration.ts
- packages/bus-core/src/service-bus/bus-instance.ts
- packages/bus-core/src/transport/in-memory-queue.spec.ts
- packages/bus-core/src/transport/in-memory-queue.ts
- packages/bus-core/src/transport/transport.ts
- packages/bus-test/src/transport.integration.ts
Exposes `bus.returnMessage()` which immediately returns the message to the queue so it can be retried. 
This is an alternative to throwing an error, which sometimes is inaccurate and can represent an exception in the code rather than the developer just wanting to retry a message because a particular state isn't updated. 
An example of this could be a message that checks if a domain has been set up and propagated correctly throughout DNS servers. Whilst an error could be thrown to indicate that the domain is not ready, it's not useful to display errors in logs for this but rather return the message for retry and check later.
> Expose `bus.returnMessage()`

- packages/bus-core/package.json
- packages/bus-core/src/message-lifecycle-context/message-lifecycle-context.ts
- packages/bus-core/src/service-bus/bus-instance-receiver.integration.ts
- packages/bus-core/src/service-bus/bus-instance.ts
When using a lambda/sqs integration, the bus is trying to delete the message when it processes successfully. This fails because the bus lib doesn't have a message object reference due to the message being passed to it using a receiver. 
Instead, on successful processing of a message the bus should simply return successfully and let the host delete the message
Similarly on error, the bus lib shouldn't attempt to return the message for retry, but instead rethrow any caught errors and let the host deal with returning the message to the queue for retry.
> Receivers shouldn't delete messages
